services:
  api:
    build: .
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
